# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production: *redis
# the redis adapter is required in development because the 'async' adapter
# works only within the same process, whereas the 'redis' adapter is
# inter-process - sidekiq runs in a different process)
development: *redis
test:
  adapter: async
