defaults: &defaults
  key: 19IGpn8RsB1wFrVNElcoyCbQd
  secret: bHZhtfzUrpbBQmgxVnflg09RzwtIlsE7Ymw7LnpTDvv7bBbpAS
  callback_url: http://myapp.com:3000/oauth/callback

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
